steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
- name: 'gcr.io/cloud-builders/npm'
  args: ['-v']
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'
